CREATE DATABASE `collectionhub_db`;
USE `collectionhub_db`;

CREATE TABLE IF NOT EXISTS `Collectors` (
    `UserID` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `Username` varchar(255) NOT NULL,
    `Password` varchar(255) NOT NULL,
    `Email` varchar(255) NOT NULL,
    `vkey`  varchar(45) NOT NULL,
    `verified`  	TINYINT(1) NOT NULL DEFAULT 0,
    `DateRegister` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `Categories` (
    `CategoryID` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `UserID` INT DEFAULT NULL,
    `Category` varchar(255) DEFAULT NULL,
    `Label` varchar(255) DEFAULT NULL,
    `DatePublished` DATE NOT NULL,
    `TimePublished` TIME(0) NOT NULL,
    INDEX `Users_ID`(UserID),
    CONSTRAINT `CE_USERS_IDENTIFICATION` FOREIGN KEY (UserID) REFERENCES Collectors(UserID) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1; 

CREATE TABLE IF NOT EXISTS `Items` (
    `ItemID` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `UserID` INT NOT NULL,
    `Item` varchar(255) DEFAULT NULL,
    `ItemPhoto` varchar(255) DEFAULT NULL,
    `Description` LONGTEXT DEFAULT NULL,
    `CategoryID` INT DEFAULT NULL,
    `IsPrivate` INT DEFAULT NULL,
    `DateAdded` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT `CE_Items_Category` FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID) ON UPDATE CASCADE,
    CONSTRAINT `CE_User_Items` FOREIGN KEY (UserID) REFERENCES Collectors(UserID) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1; 


CREATE TABLE IF NOT EXISTS `Favourites` (
    `UserID` INT NOT NULL,
    `ItemID` INT NOT NULL,
    `CategoryID` INT DEFAULT NULL,
    `DateFavourite` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT `CE_ITEMS` FOREIGN KEY (ItemID) REFERENCES Items(ItemID) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT `CE_User_Favorites` FOREIGN KEY (UserID) REFERENCES Collectors(UserID) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=latin1; 
